### ISSUE TITLE
Unhandled Rejection (Error): Unknown

### ISSUE THREAD

**Issue by akmennon** [Jaaneek/useFilePicker#27] opened 2021-10-05 06:47 UTC
I'm trying to implement any of the provided example codes but when the selected file doesn't match the given file validation React throws up an unhandled rejection. 

Uncaught (in promise) undefined - in console.

The validation is working as intended but react crashes a few frames after it

**Comment by akmennon** [comment] 2021-10-09 01:32
I'm currently on React 17.0.2 and Ubuntu 20.0.4. The validators that I've mentioned are the default ones. The parameters used are as given below.

const [openFileSelector, { filesContent, plainFiles, loading, errors }] = useFilePicker({
            readAs: 'DataURL',
            accept: 'image/*',
            multiple: false,
            // minFileSize: 0.1, // in megabytes
            maxFileSize: 1,
            imageSizeRestrictions: {
              maxHeight: 900, // in pixels
              maxWidth: 1600,
              minHeight: 200,
              minWidth: 200,
            }
        });

When the select image fails any of the given validations, React renders the given conditional elements by checking the 'errors' variable returned from the useFilePicker hook but eventually throws the error as mentioned in the previous comment.

Please note that the error is not thrown when readFilesContent is set to false.

**Comment by MrKampla** [comment] 2021-10-20 20:04
I haven't been able to reproduce this behavior. Basically, the issue You're describing might only happen on the development environment, as it can be configured to crash on unhandled rejections. It is caused by rejection of a promise in the validation process, happening before or after parsing.

The thing is, that in production environments this has no effect as it only console logs the "Uncaught (in promise)" message:
![image](https://user-images.githubusercontent.com/46401284/138129904-30fc25ac-860a-4868-a0a5-44740198bc42.png)

What environment do You use? We've tested it on CRA, Vite, Next.js, and it works perfectly without crashing.

**Comment by Jaaneek** [comment] 2021-11-01 21:26
fixed in #29

**Closed by Jaaneek** 2021-11-01 21:26 UTC
Labels: bug
